import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { execSync } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import { getBaseDomain, getRoutingMode, slugify } from '../common/networking.util';

export interface IngressRoute {
  hostname?: string;
  service: string;
}

export interface SyncIngressResult {
  configPath: string | null;
  routeCount: number;
  dnsRegistered: string[];
  restarted: boolean;
}

@Injectable()
export class TunnelService implements OnModuleInit {
  private readonly logger = new Logger(TunnelService.name);

  constructor(private prisma: PrismaService) {}

  async onModuleInit() {
    if (!this.isTunnelMode()) return;
    try {
      const result = await this.syncIngress();
      this.logger.log(
        `Tunnel synced on startup: ${result.routeCount} routes, DNS: ${result.dnsRegistered.length}, restarted: ${result.restarted}`,
      );
    } catch (error) {
      this.logger.warn(`Tunnel sync on startup failed: ${(error as Error).message}`);
    }
  }

  isTunnelMode(): boolean {
    return getRoutingMode() === 'tunnel';
  }

  private getConfigPath(): string {
    return process.env.CLOUDFLARED_CONFIG_PATH || '/var/lib/zyncloud/cloudflared-config.yml';
  }

  private getTunnelRef(): string | null {
    return process.env.CLOUDFLARE_TUNNEL_NAME || process.env.CLOUDFLARE_TUNNEL_ID || null;
  }

  async buildIngressRules(): Promise<IngressRoute[]> {
    const webHost = process.env.TUNNEL_WEB_HOST;
    const apiHost = process.env.TUNNEL_API_HOST;
    const webPort = process.env.WEB_PORT || '3000';
    const apiPort = process.env.API_PORT || '4000';

    const domains = await this.prisma.domain.findMany({
      include: { instance: { select: { name: true, internalPort: true } } },
    });

    const instances = await this.prisma.instance.findMany({
      where: { internalPort: { not: null }, status: { not: 'error' } },
      select: { name: true, internalPort: true },
    });

    const ingress: IngressRoute[] = [];
    const seen = new Set<string>();

    const add = (hostname: string | undefined | null, port: number | string | null | undefined) => {
      if (!hostname || port == null || seen.has(hostname)) return;
      seen.add(hostname);
      ingress.push({ hostname, service: `http://127.0.0.1:${port}` });
    };

    add(webHost, webPort);
    add(apiHost, apiPort);

    for (const d of domains) {
      add(d.domain, d.targetPort);
    }

    const base = getBaseDomain();
    if (base) {
      for (const inst of instances) {
        if (!inst.internalPort) continue;
        const host = `${slugify(inst.name)}.${base}`;
        if (!domains.some((d) => d.domain === host)) {
          add(host, inst.internalPort);
        }
      }
    }

    ingress.push({ service: 'http_status:404' });
    return ingress;
  }

  private buildConfigYaml(ingress: IngressRoute[]): string {
    const tunnelId = process.env.CLOUDFLARE_TUNNEL_ID;
    const credentialsFile = process.env.CLOUDFLARE_TUNNEL_CREDENTIALS;

    const header: string[] = ['# Auto-generated by ZynCloud — do not edit manually'];
    if (tunnelId) header.push(`tunnel: ${tunnelId}`);
    if (credentialsFile) header.push(`credentials-file: ${credentialsFile}`);

    const ingressLines = ingress.map((r) =>
      r.hostname
        ? `  - hostname: ${r.hostname}\n    service: ${r.service}`
        : `  - service: ${r.service}`,
    );

    return [...header, '', 'ingress:', ...ingressLines, ''].join('\n');
  }

  private async writeLocalConfig(ingress: IngressRoute[]): Promise<string | null> {
    const configPath = this.getConfigPath();
    const content = this.buildConfigYaml(ingress);

    try {
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, content, 'utf8');
      this.logger.log(`Cloudflared config written: ${configPath} (${ingress.length - 1} routes)`);
      return configPath;
    } catch (error) {
      this.logger.warn(`Could not write cloudflared config: ${(error as Error).message}`);
      return null;
    }
  }

  private collectHostnames(ingress: IngressRoute[]): string[] {
    return ingress
      .map((r) => r.hostname)
      .filter((h): h is string => Boolean(h));
  }

  private runHostCommand(command: string, label: string): boolean {
    try {
      execSync(command, { stdio: 'pipe', timeout: 30_000 });
      this.logger.log(label);
      return true;
    } catch (error) {
      this.logger.warn(`${label} failed: ${(error as Error).message}`);
      return false;
    }
  }

  private buildRestartCommand(): string | null {
    if (process.env.CLOUDFLARED_RESTART_CMD) {
      return process.env.CLOUDFLARED_RESTART_CMD;
    }

    if (process.env.HOST_CONSOLE_ENABLED !== 'true') return null;

    const keyPath = process.env.HOST_CONSOLE_SSH_KEY_PATH || '/run/secrets/zyncloud/host_console_key';
    const host = process.env.HOST_CONSOLE_SSH_HOST || 'host.docker.internal';
    const user = process.env.HOST_CONSOLE_SSH_USER;
    if (!user) return null;

    const port = process.env.HOST_CONSOLE_SSH_PORT || '22';
    const portFlag = port !== '22' ? `-p ${port} ` : '';
    return `ssh -i ${keyPath} -o StrictHostKeyChecking=no -o BatchMode=yes ${portFlag}${user}@${host} "sudo systemctl restart cloudflared"`;
  }

  private restartCloudflared(): boolean {
    const cmd = this.buildRestartCommand();
    if (!cmd) {
      this.logger.warn(
        'Set CLOUDFLARED_RESTART_CMD or HOST_CONSOLE SSH to auto-restart cloudflared after route changes',
      );
      return false;
    }
    return this.runHostCommand(cmd, 'cloudflared restarted');
  }

  private registerDns(hostname: string): boolean {
    const tunnelRef = this.getTunnelRef();
    if (!tunnelRef) {
      this.logger.debug(`Skipping DNS for ${hostname}: CLOUDFLARE_TUNNEL_NAME not set`);
      return false;
    }

    const cloudflaredBin = process.env.CLOUDFLARED_BIN || 'cloudflared';
    const cmd = `${cloudflaredBin} tunnel route dns ${tunnelRef} ${hostname}`;
    return this.runHostCommand(cmd, `DNS registered: ${hostname}`);
  }

  private registerDnsForHostnames(hostnames: IngressRoute[]): string[] {
    const tunnelRef = this.getTunnelRef();
    if (!tunnelRef) return [];

    const webHost = process.env.TUNNEL_WEB_HOST;
    const apiHost = process.env.TUNNEL_API_HOST;
    const skip = new Set([webHost, apiHost].filter(Boolean) as string[]);

    const registered: string[] = [];
    for (const hostname of this.collectHostnames(hostnames)) {
      if (skip.has(hostname)) continue;
      if (this.registerDns(hostname)) {
        registered.push(hostname);
      }
    }
    return registered;
  }

  async syncIngress(): Promise<SyncIngressResult> {
    if (!this.isTunnelMode()) {
      return { configPath: null, routeCount: 0, dnsRegistered: [], restarted: false };
    }

    const ingress = await this.buildIngressRules();
    const configPath = await this.writeLocalConfig(ingress);
    const dnsRegistered = this.registerDnsForHostnames(ingress);
    const restarted = configPath ? this.restartCloudflared() : false;

    return {
      configPath,
      routeCount: ingress.length - 1,
      dnsRegistered,
      restarted,
    };
  }
}
