import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { execSync } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import { getBaseDomain, getRoutingMode, slugify } from '../common/networking.util';

export interface IngressRoute {
  hostname?: string;
  service: string;
}

export interface SyncIngressResult {
  configPath: string | null;
  routeCount: number;
  dnsRegistered: string[];
  restarted: boolean;
  cloudflareSynced: boolean;
  cloudflareError?: string;
  hostnames: string[];
}

@Injectable()
export class TunnelService implements OnModuleInit {
  private readonly logger = new Logger(TunnelService.name);

  constructor(private prisma: PrismaService) {}

  async onModuleInit() {
    if (!this.isTunnelMode()) return;
    try {
      const result = await this.syncIngress();
      this.logger.log(
        `Tunnel synced on startup: ${result.routeCount} routes, DNS: ${result.dnsRegistered.length}, restarted: ${result.restarted}`,
      );
    } catch (error) {
      this.logger.warn(`Tunnel sync on startup failed: ${(error as Error).message}`);
    }
  }

  isTunnelMode(): boolean {
    return getRoutingMode() === 'tunnel';
  }

  private getConfigPath(): string {
    return process.env.CLOUDFLARED_CONFIG_PATH || '/var/lib/zyncloud/cloudflared-config.yml';
  }

  private getTunnelRef(): string | null {
    return process.env.CLOUDFLARE_TUNNEL_NAME || process.env.CLOUDFLARE_TUNNEL_ID || null;
  }

  async buildIngressRules(): Promise<IngressRoute[]> {
    const webHost = process.env.TUNNEL_WEB_HOST;
    const apiHost = process.env.TUNNEL_API_HOST;
    const webPort = process.env.WEB_PORT || '3000';
    const apiPort = process.env.API_PORT || '4000';

    const domains = await this.prisma.domain.findMany({
      include: { instance: { select: { name: true, internalPort: true } } },
    });

    const instances = await this.prisma.instance.findMany({
      where: { internalPort: { not: null }, status: { not: 'error' } },
      select: { name: true, internalPort: true },
    });

    const ingress: IngressRoute[] = [];
    const seen = new Set<string>();

    const add = (hostname: string | undefined | null, port: number | string | null | undefined) => {
      if (!hostname || port == null || seen.has(hostname)) return;
      seen.add(hostname);
      ingress.push({ hostname, service: `http://127.0.0.1:${port}` });
    };

    add(webHost, webPort);
    add(apiHost, apiPort);

    for (const d of domains) {
      add(d.domain, d.targetPort);
    }

    const base = getBaseDomain();
    if (base) {
      for (const inst of instances) {
        if (!inst.internalPort) continue;
        const host = `${slugify(inst.name)}.${base}`;
        if (!domains.some((d) => d.domain === host)) {
          add(host, inst.internalPort);
        }
      }
    }

    ingress.push({ service: 'http_status:404' });
    return ingress;
  }

  private buildConfigYaml(ingress: IngressRoute[]): string {
    const tunnelId = process.env.CLOUDFLARE_TUNNEL_ID;
    const credentialsFile = process.env.CLOUDFLARE_TUNNEL_CREDENTIALS;

    const header: string[] = ['# Auto-generated by ZynCloud — do not edit manually'];
    if (tunnelId) header.push(`tunnel: ${tunnelId}`);
    if (credentialsFile) header.push(`credentials-file: ${credentialsFile}`);

    const ingressLines = ingress.map((r) =>
      r.hostname
        ? `  - hostname: ${r.hostname}\n    service: ${r.service}`
        : `  - service: ${r.service}`,
    );

    return [...header, '', 'ingress:', ...ingressLines, ''].join('\n');
  }

  private async writeLocalConfig(ingress: IngressRoute[]): Promise<string | null> {
    const configPath = this.getConfigPath();
    const content = this.buildConfigYaml(ingress);

    try {
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, content, 'utf8');
      this.logger.log(`Cloudflared config written: ${configPath} (${ingress.length - 1} routes)`);
      return configPath;
    } catch (error) {
      this.logger.warn(`Could not write cloudflared config: ${(error as Error).message}`);
      return null;
    }
  }

  private collectHostnames(ingress: IngressRoute[]): string[] {
    return ingress
      .map((r) => r.hostname)
      .filter((h): h is string => Boolean(h));
  }

  private buildSshExec(remoteCommand: string): string | null {
    const user = process.env.HOST_CONSOLE_SSH_USER;
    if (!user) return null;

    const useSsh =
      process.env.TUNNEL_USE_SSH === 'true' || process.env.HOST_CONSOLE_ENABLED === 'true';
    if (!useSsh) return null;

    const keyPath = process.env.HOST_CONSOLE_SSH_KEY_PATH || '/run/secrets/zyncloud/host_console_key';
    const host = process.env.HOST_CONSOLE_SSH_HOST || 'host.docker.internal';
    const port = process.env.HOST_CONSOLE_SSH_PORT || '22';
    const portFlag = port !== '22' ? `-p ${port} ` : '';
    const escaped = remoteCommand.replace(/'/g, `'\\''`);
    return `ssh -i ${keyPath} -o StrictHostKeyChecking=no -o BatchMode=yes -o IdentitiesOnly=yes ${portFlag}${user}@${host} '${escaped}'`;
  }

  private runCommand(command: string, label: string): boolean {
    const sshWrapped = this.buildSshExec(command);
    const cmd = sshWrapped ?? command;
    try {
      execSync(cmd, { stdio: 'pipe', timeout: 60_000 });
      this.logger.log(label);
      return true;
    } catch (error) {
      this.logger.warn(`${label} failed: ${(error as Error).message}`);
      return false;
    }
  }

  private buildRestartCommand(): string {
    if (process.env.CLOUDFLARED_RESTART_CMD) {
      return process.env.CLOUDFLARED_RESTART_CMD;
    }
    return 'sudo systemctl restart cloudflared';
  }

  private restartCloudflared(): boolean {
    return this.runCommand(this.buildRestartCommand(), 'cloudflared restarted');
  }

  private getCloudflaredBin(): string {
    return process.env.CLOUDFLARED_BIN || 'cloudflared';
  }

  private registerDns(hostname: string): boolean {
    const tunnelRef = this.getTunnelRef();
    if (!tunnelRef) {
      this.logger.debug(`Skipping DNS for ${hostname}: CLOUDFLARE_TUNNEL_NAME not set`);
      return false;
    }

    const cmd = `${this.getCloudflaredBin()} tunnel route dns ${tunnelRef} ${hostname}`;
    return this.runCommand(cmd, `DNS registered: ${hostname}`);
  }

  private async pushIngressToCloudflare(
    ingress: IngressRoute[],
  ): Promise<{ ok: boolean; error?: string }> {
    const token = process.env.CLOUDFLARE_API_TOKEN;
    const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
    const tunnelId = process.env.CLOUDFLARE_TUNNEL_ID;

    if (!token || !accountId || !tunnelId) {
      return {
        ok: false,
        error: 'Falta CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID o CLOUDFLARE_TUNNEL_ID en el servidor',
      };
    }

    const cfIngress = ingress.map((r) =>
      r.hostname ? { hostname: r.hostname, service: r.service } : { service: r.service },
    );

    try {
      const res = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${tunnelId}/configurations`,
        {
          method: 'PUT',
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ config: { ingress: cfIngress } }),
        },
      );

      const body = (await res.json()) as { success?: boolean; errors?: { message: string }[] };
      if (!res.ok || !body.success) {
        const msg = body.errors?.map((e) => e.message).join('; ') || res.statusText;
        this.logger.warn(`Cloudflare tunnel API failed: ${msg}`);
        return { ok: false, error: msg };
      }

      this.logger.log(`Cloudflare tunnel API updated (${cfIngress.length - 1} routes)`);
      return { ok: true };
    } catch (error) {
      const msg = (error as Error).message;
      this.logger.warn(`Cloudflare tunnel API error: ${msg}`);
      return { ok: false, error: msg };
    }
  }

  async fetchCloudflareHostnames(): Promise<string[]> {
    const token = process.env.CLOUDFLARE_API_TOKEN;
    const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
    const tunnelId = process.env.CLOUDFLARE_TUNNEL_ID;
    if (!token || !accountId || !tunnelId) return [];

    try {
      const res = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${tunnelId}/configurations`,
        { headers: { Authorization: `Bearer ${token}` } },
      );
      const body = (await res.json()) as {
        success?: boolean;
        result?: { config?: { ingress?: { hostname?: string }[] } };
      };
      if (!body.success || !body.result?.config?.ingress) return [];
      return body.result.config.ingress
        .map((r) => r.hostname)
        .filter((h): h is string => Boolean(h));
    } catch {
      return [];
    }
  }

  async isHostnameRouted(hostname: string): Promise<boolean> {
    const cfHosts = await this.fetchCloudflareHostnames();
    if (cfHosts.includes(hostname)) return true;

    try {
      const configPath = this.getConfigPath();
      const content = await fs.readFile(configPath, 'utf8');
      return content.includes(`hostname: ${hostname}`);
    } catch {
      return false;
    }
  }

  private registerDnsForHostnames(ingress: IngressRoute[]): string[] {
    const tunnelRef = this.getTunnelRef();
    if (!tunnelRef) return [];

    const webHost = process.env.TUNNEL_WEB_HOST;
    const apiHost = process.env.TUNNEL_API_HOST;
    const skip = new Set([webHost, apiHost].filter(Boolean) as string[]);

    const registered: string[] = [];
    for (const hostname of this.collectHostnames(ingress)) {
      if (skip.has(hostname)) continue;
      if (this.registerDns(hostname)) {
        registered.push(hostname);
      }
    }
    return registered;
  }

  async syncIngress(): Promise<SyncIngressResult> {
    if (!this.isTunnelMode()) {
      return {
        configPath: null,
        routeCount: 0,
        dnsRegistered: [],
        restarted: false,
        cloudflareSynced: false,
        hostnames: [],
      };
    }

    const ingress = await this.buildIngressRules();
    const hostnames = this.collectHostnames(ingress);

    const cfPush = await this.pushIngressToCloudflare(ingress);
    const cloudflareSynced = cfPush.ok;
    const configPath = await this.writeLocalConfig(ingress);

    const dnsRegistered = cloudflareSynced
      ? []
      : this.registerDnsForHostnames(ingress);

    // Restart cloudflared whenever config was written, regardless of API sync,
    // because locally-managed tunnels read from the file and need a reload.
    const restarted = configPath ? this.restartCloudflared() : false;

    if (!cloudflareSynced && !restarted) {
      this.logger.warn(
        `Tunnel sync incomplete: API ${cfPush.error ?? 'unknown'}, cloudflared restart also failed.`,
      );
    }

    return {
      configPath,
      routeCount: ingress.length - 1,
      dnsRegistered,
      restarted,
      cloudflareSynced,
      cloudflareError: cfPush.error,
      hostnames,
    };
  }
}
