import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import * as fs from 'fs/promises';
import * as path from 'path';
import { getBaseDomain, getRoutingMode, slugify } from '../common/networking.util';

@Injectable()
export class TunnelService {
  private readonly logger = new Logger(TunnelService.name);

  constructor(private prisma: PrismaService) {}

  isTunnelMode(): boolean {
    return getRoutingMode() === 'tunnel';
  }

  async syncIngress(): Promise<string | null> {
    if (!this.isTunnelMode()) return null;

    const configPath =
      process.env.CLOUDFLARED_CONFIG_PATH || '/var/lib/zyncloud/cloudflared-ingress.yml';

    const webHost = process.env.TUNNEL_WEB_HOST;
    const apiHost = process.env.TUNNEL_API_HOST;
    const webPort = process.env.WEB_PORT || '3000';
    const apiPort = process.env.API_PORT || '4000';

    const domains = await this.prisma.domain.findMany({
      include: { instance: { select: { name: true, internalPort: true } } },
    });

    const instances = await this.prisma.instance.findMany({
      where: { internalPort: { not: null }, status: { not: 'error' } },
      select: { name: true, internalPort: true },
    });

    const ingress: { hostname: string; service: string }[] = [];
    const seen = new Set<string>();

    const add = (hostname: string | undefined | null, port: number | string | null | undefined) => {
      if (!hostname || port == null || seen.has(hostname)) return;
      seen.add(hostname);
      ingress.push({ hostname, service: `http://127.0.0.1:${port}` });
    };

    add(webHost, webPort);
    add(apiHost, apiPort);

    for (const d of domains) {
      add(d.domain, d.targetPort);
    }

    const base = getBaseDomain();
    if (base) {
      for (const inst of instances) {
        if (!inst.internalPort) continue;
        const host = `${slugify(inst.name)}.${base}`;
        if (!domains.some((d) => d.domain === host)) {
          add(host, inst.internalPort);
        }
      }
    }

    ingress.push({ hostname: '', service: 'http_status:404' });

    const lines = [
      '# Auto-generated by ZynCloud',
      'ingress:',
      ...ingress.map((r) =>
        r.hostname
          ? `  - hostname: ${r.hostname}\n    service: ${r.service}`
          : `  - service: ${r.service}`,
      ),
    ];

    const content = lines.join('\n') + '\n';

    try {
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, content, 'utf8');
      this.logger.log(`Cloudflared ingress: ${configPath} (${ingress.length - 1} routes)`);
      return configPath;
    } catch (error) {
      this.logger.warn(`Could not write cloudflared config: ${(error as Error).message}`);
      return null;
    }
  }
}
